package site.iplease.irdserver.global.error

enum class ErrorStatus {
    ALREADY_DEMANDED_ASSIGN_IP,
    UNKNOWN_ASSIGN_IP,
    PERMISSION_DENIED,
    UNKNOWN_DEMAND,
    ALREADY_ACCEPTED_ASSIGN_IP,
    ALREADY_RESERVED_ASSIGN_IP,
    JWT_ERROR,
    POLICY_VIOLATION_ERROR,
    UNKNOWN_ACCOUNT_ERROR,
    WRONG_EMAIL_TOKEN_ERROR,
    WRONG_DEPARTMENT_OR_STUDENT_NUMBER_ERROR,
    CONSTRAINT_VIOLATION_ERROR,
    WRONG_AUTH_CODE,
    API_ERROR,
}
